### ISSUE TITLE
Version 1.7.0 on PyPI does not include the formats folder

### ISSUE THREAD

**Issue by PalmtopTiger** [tkarabela/pysubs2#92]
Both wheel and gzip.

Error message:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\pysubs2.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\pysubs2\__init__.py", line 1, in <module>
    from .ssafile import SSAFile
  File "C:\Python312\Lib\site-packages\pysubs2\ssafile.py", line 584, in <module>
    from .formats import autodetect_format, get_format_class, get_format_identifier  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pysubs2.formats'
```

**Comment by Nisekoi-1** [comment]
yes, same issue

**Comment by tkarabela** [comment]
I see, sorry about that! I've yanked the 1.7.0 release and will release 1.7.1 that will fix this.

**Comment by PalmtopTiger** [comment]
Version 1.7.1 is ok.

**Comment by Nisekoi-1** [comment]
thanks
