### ISSUE TITLE
FormatAutodetectionError crashes multiprocessing.pool

### ISSUE THREAD

**Issue by klementng** [tkarabela/pysubs2#97]
In my own [project](https://github.com/klementng/subtitle-extract/), I've been running into issues when using the python multiprocessing library in together with pysub2. 

From my observations, when the FormatAutodetectionError exception is raised, the whole multiprocessing crashes with the following trackback
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/usr/local/lib/python3.12/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FormatAutodetectionError.__init__() missing 1 required positional argument: 'formats'
```

Upon further investigation, the issues seem to be caused by the transferring of the exception from the thread to the main program where the exception which causes in the formats arg being lost / not passed. 

Reproducible code example
```python
import traceback
import multiprocessing
import random
import time
import pysubs2

process_count = 0


def _run_callback(result):
    global process_count
    process_count += 1

    print(process_count)


def _error_callback(error):
    print("An error has occurred")
    traceback.print_exception(type(error), error, error.__traceback__)


def _f():

    if random.randint(1, 50) == 1:
        raise pysubs2.FormatAutodetectionError("", [])

    if random.randint(1, 10) == 1:
        raise Exception("Regular exception is properly handled by multiprocessing")

    return "ABC"


with multiprocessing.Pool(4) as pool:
    for _ in range(1000):
        pool.apply_async(
            _f,
            callback=_run_callback,
            error_callback=_error_callback,
        )

    pool.close()
    pool.join()


```

Related stackoverflow issue: https://stackoverflow.com/questions/70883678/python-multiprocessing-get-hung

---
My fix for this issue is to simply passing the ext into the _format kwargs to prevent the autodetection function from running
```
pysubs2.load(path, format_=ext)
```

**Comment by tkarabela** [comment]
@klementng Thanks for the report, I'll look into it.

**Comment by tkarabela** [comment]
Please upgrade to version 1.7.3, it should be fixed :)
